name: android_app_builder
description: Custom WebView App Builder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  wakelock_plus: ^1.1.4
  url_launcher: ^6.2.3
  flutter_native_splash: ^2.3.9  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  
    - assets/offline.html

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash.png
  android: true
  ios: false
